DROP DATABASE IF EXISTS `BD_LISTIFY`;
CREATE DATABASE IF NOT EXISTS `BD_LISTIFY`;
USE `BD_LISTIFY`;

-- LEVELS
-- ---------------------------------
CREATE TABLE IF NOT EXISTS `LEVELS` (
  `LE_ID_LEVEL` INT(10) NOT NULL AUTO_INCREMENT,
  `LE_EXPERIENCE` INT(10) NOT NULL,
  `LE_NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`LE_ID_LEVEL`),
  INDEX `IX_LE_NAME` (`LE_NAME`) 
);

-- ROLES
-- ---------------------------------
CREATE TABLE IF NOT EXISTS `ROLES` (
  `RO_ID_ROLE` INT(10) NOT NULL AUTO_INCREMENT,
  `RO_NAME` VARCHAR(50) NOT NULL,
  `RO_DETAIL` VARCHAR(50) NOT NULL,
  `RO_ACTIVE` TINYINT(1) NOT NULL,
  PRIMARY KEY (`RO_ID_ROLE`),
  INDEX `IX_RO_ID_ROLE` (`RO_ID_ROLE`) 
  );

-- USERS
-- ---------------------------------
CREATE TABLE IF NOT EXISTS `USERS` (
  `US_ID_USER` INT(10) NOT NULL AUTO_INCREMENT,
  `US_NAME` VARCHAR(50) NOT NULL,
  `US_NICKNAME` VARCHAR(50) NOT NULL,
  `US_LASTNAME` VARCHAR(50) NOT NULL,
  `US_EMAIL` VARCHAR(100) NOT NULL,
  `US_PASSWORD` VARCHAR(50) NOT NULL,
  `US_EXPERIENCE` INT(10) NOT NULL,
  `US_LEVEL_NAME` VARCHAR(50) NOT NULL,
  `US_LEVEL` INT(2) NOT NULL,
  `US_ID_ROLE` INT(10) NOT NULL,
  `US_ACTIVE` TINYINT(1) NOT NULL,
  PRIMARY KEY (`US_ID_USER`),
  INDEX `IX_US_ID_USER` (`US_ID_USER`), 
  CONSTRAINT `FK_USERS_LEVELS`
    FOREIGN KEY (`US_LEVEL_NAME`)
    REFERENCES `BD_LISTIFY`.`LEVELS` (`LE_NAME`),
  CONSTRAINT `FK_USERS_ROLES`
    FOREIGN KEY (`US_ID_ROLE`)
    REFERENCES `BD_LISTIFY`.`ROLES` (`RO_ID_ROLE`)
);

-- TASKS
-- ---------------------------------
CREATE TABLE IF NOT EXISTS `TASKS` (
  `TA_ID_TASK` INT NOT NULL AUTO_INCREMENT,
  `TA_TITLE` VARCHAR(50) NOT NULL,
  `TA_DESCRIPTION` VARCHAR(255),
  `TA_PRIORITY` INT NOT NULL,
  `TA_EXPERIENCE_POINTS` INT NOT NULL,
  `TA_STATUS` TINYINT NOT NULL,
  `TA_CREATION_DATE` DATETIME NOT NULL,
  `TA_END_DATE` DATETIME,
  `TA_ID_USER` INT,
  PRIMARY KEY (`TA_ID_TASK`),
  CONSTRAINT `FK_TASKS_USERS`
    FOREIGN KEY (`TA_ID_USER`)
    REFERENCES `BD_LISTIFY`.`USERS` (`US_ID_USER`)
);

-- ERRORS
-- ---------------------------------
CREATE TABLE IF NOT EXISTS `ERRORS` (
  `ER_CODE` VARCHAR(255) NOT NULL,
  `ER_DESCRIPTION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ER_CODE`)
);

-- PERMISSIONS
-- ---------------------------------
CREATE TABLE IF NOT EXISTS `PERMISSIONS` (
  `PE_ID_PERMISSION` INT(10) NOT NULL AUTO_INCREMENT,
  `PE_NAME` VARCHAR(50) NOT NULL,
  `PE_DESCRIPTION` VARCHAR(255),
  PRIMARY KEY (`PE_ID_PERMISSION`),
  INDEX `IX_PE_ID_PERMISSION` (`PE_ID_PERMISSION`)
);

-- ROLE_PERMISSIONS
-- ---------------------------------
CREATE TABLE IF NOT EXISTS `ROLE_PERMISSIONS` (
  `RP_ID_ROLE_PERMISSION` INT(10) NOT NULL AUTO_INCREMENT,
  `RP_ID_ROLE` INT(10) NOT NULL,
  `RP_ID_PERMISSION` INT(10) NOT NULL,
  PRIMARY KEY (`RP_ID_ROLE_PERMISSION`),
  CONSTRAINT `FK_ROLE_PERMISSIONS_ROLES`
    FOREIGN KEY (`RP_ID_ROLE`)
    REFERENCES `BD_LISTIFY`.`ROLES` (`RO_ID_ROLE`),
  CONSTRAINT `FK_ROLE_PERMISSIONS_PERMISSIONS`
    FOREIGN KEY (`RP_ID_PERMISSION`)
    REFERENCES `BD_LISTIFY`.`PERMISSIONS` (`PE_ID_PERMISSION`)
);



