USE BD_LISTIFY;

INSERT INTO `PERMISSIONS`
(`PE_ID_PERMISSION`,
`PE_NAME`,
`PE_DESCRIPTION`)
VALUES (1,
'CREATE_USER',
'Crear usuario');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (2, 
'DELETE_USER', 
'Eliminar usuario');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (3, 
'EDIT_USER', 
'Editar usuario');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (4, 
'VIEW_USERS', 
'Ver usuarios');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (5, 
'CREATE_ROLE', 
'Crear rol');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (6, 
'EDIT_ROLE', 
'Editar rol');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (7, 
'DELETE_ROLE', 
'Eliminar rol');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (8, 
'VIEW_ROLES', 
'Ver roles');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`,
`PE_NAME`,
`PE_DESCRIPTION`)
VALUES (9,
'CREATE_ROLE_PERMISSION',
'Crear permiso a rol');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (10, 
'DELETE_ROLE_PERMISSION', 
'eliminar permiso a rol');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (11, 
'EDIT_ROLE_PERMISSION', 
'Editar permiso de rol');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (12, 
'VIEW_ROLE_PERMISSIONS', 
'Ver permisos de rol');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (13, 
'REQUEST_USER_DELETION', 
'Solicitar eliminacion de usuario');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (14, 
'CREATE_TASK', 
'Crear tarea');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (15, 
'DELETE_TASK', 
'Eliminar tarea');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (16, 
'EDIT_TASK', 
'Editar tarea');

INSERT INTO `PERMISSIONS` 
(`PE_ID_PERMISSION`, 
`PE_NAME`, 
`PE_DESCRIPTION`) 
VALUES (17, 
'VIEW_TASKS', 
'Ver tareas');






